# Optimized hyperparameters for 3D Planetary Gravity Simulation
# Generated by enhanced hyperparameter optimization (v2)

OPTIMAL_CONFIG = {
    # Core parameters
    'dt': 1800,  # seconds (0.50 hours)
    'softening': 100000000.0,  # meters
    'integration_method': 'verlet',
    'adaptive_dt': True,
    'num_steps': 1000,

    # Performance metrics
    'overall_score': 100.00,
    'energy_error': 0.000000,  # percent
    'momentum_error': 0.000000,  # percent
    'orbit_deviation': 0.0058,  # percent
    'energy_drift': 0.000000,  # percent

    # Component scores
    'energy_score': 100.00,
    'momentum_score': 100.00,
    'orbit_stability_score': 99.99,
    'energy_drift_score': 100.00,
}

# Usage example:
# from optimal_config import OPTIMAL_CONFIG
# from hyperparameter_optimization import OptimizedGravitySimulation
# from main import create_solar_system_inner
#
# bodies = create_solar_system_inner()
# sim = OptimizedGravitySimulation(
#     bodies,
#     dt=OPTIMAL_CONFIG['dt'],
#     softening=OPTIMAL_CONFIG['softening'],
#     integration_method=OPTIMAL_CONFIG['integration_method']
# )
# sim.run(OPTIMAL_CONFIG['num_steps'])
