# Optimized hyperparameters for 3D Planetary Gravity Simulation
# Generated by hyperparameter optimization

OPTIMAL_CONFIG = {
    'dt': 3600,  # Time step in seconds (1.00 hours)
    'softening': 0.0,  # Softening parameter in meters
    'integration_method': 'rk4',  # Integration method
    'num_steps': 1000,  # Number of steps

    # Performance metrics
    'overall_score': 100.00,
    'energy_error': 0.0000,  # percent
    'momentum_error': 0.0000,  # percent
}
