"""
Verify operation counts by manual calculation
"""

print("=" * 80)
print("MANUAL OPERATION COUNT VERIFICATION")
print("=" * 80)

print("\n1. STANDARD 3x3 ALGORITHM")
print("-" * 80)
print("C[i,j] = sum(A[i,k] * B[k,j] for k in 0..2)")
print()
print("For each of 9 output elements:")
print("  - 3 multiplications")
print("  - 2 additions (k=1 and k=2)")
print()
print("Total: 9 × 3 = 27 multiplications")
print("       9 × 2 = 18 additions")
print("       Total: 45 operations ✓")

print("\n2. BLOCK-STRASSEN ALGORITHM")
print("-" * 80)
print("Component: Strassen 2x2 on A11 × B11")
print("  - 7 multiplications")
print("  - Preprocessing: 7 additions (2+1+1+1+1+2+2)")
print("  - Postprocessing: 8 additions (3+1+1+3)")
print("  - Subtotal: 7 mults, 15 adds")
print()
print("Component: Border multiplications")
print("  - Q = u @ y: 4 mults (2x1 × 1x2 outer product)")
print("  - r = A11 @ x: 4 mults, 2 adds (2x2 × 2x1)")
print("  - s = u * beta: 2 mults (2x1 scalar)")
print("  - t = v @ B11: 4 mults, 2 adds (1x2 × 2x2)")
print("  - w = alpha * y: 2 mults (scalar × 1x2)")
print("  - z = v @ x: 2 mults, 1 add (1x2 × 2x1 dot)")
print("  - gamma = alpha * beta: 1 mult")
print("  - Subtotal: 19 mults, 5 adds")
print()
print("Component: Block assembly")
print("  - C11 = P + Q: 4 adds (2x2 + 2x2)")
print("  - C12 = r + s: 2 adds (2x1 + 2x1)")
print("  - C21 = t + w: 2 adds (1x2 + 1x2)")
print("  - C22 = z + gamma: 1 add (scalar + scalar)")
print("  - Subtotal: 0 mults, 9 adds")
print()
print("Total: (7 + 19 + 0) = 26 multiplications ✓")
print("       (15 + 5 + 9) = 29 additions")
print("       Total: 55 operations")
print()
print("Note: My implementation counted 32 additions (off by 3)")

print("\n3. BLOCK-STANDARD ALGORITHM")
print("-" * 80)
print("Component: Standard 2x2 on A11 × B11")
print("  - 8 multiplications")
print("  - 4 additions")
print("  - Subtotal: 8 mults, 4 adds")
print()
print("Component: Border multiplications (same as Block-Strassen)")
print("  - Subtotal: 19 mults, 5 adds")
print()
print("Component: Block assembly (same as Block-Strassen)")
print("  - Subtotal: 0 mults, 9 adds")
print()
print("Total: (8 + 19 + 0) = 27 multiplications")
print("       (4 + 5 + 9) = 18 additions")
print("       Total: 45 operations ✓")

print("\n4. COMPARISON")
print("-" * 80)
print("Algorithm                  Mults  Adds  Total")
print("Standard                     27    18     45")
print("Block-Standard               27    18     45")
print("Block-Strassen               26    29     55")
print()
print("Key insight: Block decomposition alone doesn't help.")
print("Only Strassen 2x2 reduces multiplications (by 1).")
print("=" * 80)
